//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("confirmationRequest", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class ConfirmationRequest {
    
    private Display displayField;
    
    private string timeoutField;
    
    private string timeoutReminderField;
    
    private DisplayType displayTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Display display {
        get {
            return this.displayField;
        }
        set {
            this.displayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string timeout {
        get {
            return this.timeoutField;
        }
        set {
            this.timeoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string timeoutReminder {
        get {
            return this.timeoutReminderField;
        }
        set {
            this.timeoutReminderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DisplayType displayType {
        get {
            return this.displayTypeField;
        }
        set {
            this.displayTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public partial class Display {
    
    private string[] lineField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public partial class PointBalance {
    
    private ulong pointsPreviousField;
    
    private ulong pointEarnedField;
    
    private ulong pointsRedeemedField;
    
    private ulong pointsAvailableField;
    
    private bool pointsAvailableFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong pointsPrevious {
        get {
            return this.pointsPreviousField;
        }
        set {
            this.pointsPreviousField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong pointEarned {
        get {
            return this.pointEarnedField;
        }
        set {
            this.pointEarnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong pointsRedeemed {
        get {
            return this.pointsRedeemedField;
        }
        set {
            this.pointsRedeemedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong pointsAvailable {
        get {
            return this.pointsAvailableField;
        }
        set {
            this.pointsAvailableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pointsAvailableSpecified {
        get {
            return this.pointsAvailableFieldSpecified;
        }
        set {
            this.pointsAvailableFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public partial class RedemptionItem {
    
    private string productCodeField;
    
    private string descriptionField;
    
    private ulong pointsField;
    
    private ulong priceField;
    
    private bool priceFieldSpecified;
    
    private CurrencyType priceCurrField;
    
    private bool priceCurrFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string productCode {
        get {
            return this.productCodeField;
        }
        set {
            this.productCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong points {
        get {
            return this.pointsField;
        }
        set {
            this.pointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceSpecified {
        get {
            return this.priceFieldSpecified;
        }
        set {
            this.priceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CurrencyType priceCurr {
        get {
            return this.priceCurrField;
        }
        set {
            this.priceCurrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceCurrSpecified {
        get {
            return this.priceCurrFieldSpecified;
        }
        set {
            this.priceCurrFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public enum CurrencyType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("020")]
    Item020,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("784")]
    Item784,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("004")]
    Item004,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("971")]
    Item971,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("008")]
    Item008,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("051")]
    Item051,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("532")]
    Item532,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("973")]
    Item973,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("024")]
    Item024,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("032")]
    Item032,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("040")]
    Item040,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("036")]
    Item036,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("533")]
    Item533,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("031")]
    Item031,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("977")]
    Item977,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("052")]
    Item052,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("050")]
    Item050,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("056")]
    Item056,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("100")]
    Item100,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("975")]
    Item975,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("048")]
    Item048,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("108")]
    Item108,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("060")]
    Item060,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("096")]
    Item096,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("068")]
    Item068,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("984")]
    Item984,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("986")]
    Item986,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("044")]
    Item044,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("064")]
    Item064,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("072")]
    Item072,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("974")]
    Item974,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("084")]
    Item084,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("124")]
    Item124,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("976")]
    Item976,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("947")]
    Item947,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("756")]
    Item756,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("948")]
    Item948,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("990")]
    Item990,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("152")]
    Item152,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("156")]
    Item156,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("170")]
    Item170,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("188")]
    Item188,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("891")]
    Item891,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("200")]
    Item200,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("192")]
    Item192,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("132")]
    Item132,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("196")]
    Item196,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("203")]
    Item203,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("276")]
    Item276,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("262")]
    Item262,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("208")]
    Item208,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("214")]
    Item214,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("012")]
    Item012,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("218")]
    Item218,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("233")]
    Item233,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("818")]
    Item818,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("232")]
    Item232,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("724")]
    Item724,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("230")]
    Item230,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("978")]
    Item978,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("246")]
    Item246,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("242")]
    Item242,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("238")]
    Item238,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("250")]
    Item250,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("826")]
    Item826,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("981")]
    Item981,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("288")]
    Item288,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("936")]
    Item936,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("292")]
    Item292,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("270")]
    Item270,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("324")]
    Item324,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("300")]
    Item300,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("320")]
    Item320,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("328")]
    Item328,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("344")]
    Item344,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("340")]
    Item340,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("191")]
    Item191,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("332")]
    Item332,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("348")]
    Item348,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("360")]
    Item360,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("372")]
    Item372,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("376")]
    Item376,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("356")]
    Item356,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("368")]
    Item368,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("364")]
    Item364,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("352")]
    Item352,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("380")]
    Item380,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("388")]
    Item388,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("400")]
    Item400,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("392")]
    Item392,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("404")]
    Item404,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("417")]
    Item417,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("116")]
    Item116,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("174")]
    Item174,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("408")]
    Item408,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("410")]
    Item410,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("414")]
    Item414,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("136")]
    Item136,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("398")]
    Item398,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("418")]
    Item418,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("422")]
    Item422,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("144")]
    Item144,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("430")]
    Item430,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("426")]
    Item426,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("440")]
    Item440,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("442")]
    Item442,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("428")]
    Item428,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("434")]
    Item434,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("504")]
    Item504,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("498")]
    Item498,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("969")]
    Item969,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("450")]
    Item450,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("807")]
    Item807,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("104")]
    Item104,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("496")]
    Item496,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("446")]
    Item446,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("478")]
    Item478,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("470")]
    Item470,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("480")]
    Item480,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("462")]
    Item462,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("454")]
    Item454,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("484")]
    Item484,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("979")]
    Item979,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("458")]
    Item458,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("508")]
    Item508,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("943")]
    Item943,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("516")]
    Item516,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("566")]
    Item566,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("558")]
    Item558,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("528")]
    Item528,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("578")]
    Item578,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("524")]
    Item524,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("554")]
    Item554,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("512")]
    Item512,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("590")]
    Item590,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("604")]
    Item604,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("598")]
    Item598,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("608")]
    Item608,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("586")]
    Item586,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("985")]
    Item985,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("620")]
    Item620,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("600")]
    Item600,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("634")]
    Item634,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("642")]
    Item642,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("946")]
    Item946,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("941")]
    Item941,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("643")]
    Item643,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("810")]
    Item810,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("646")]
    Item646,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("682")]
    Item682,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("090")]
    Item090,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("690")]
    Item690,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("736")]
    Item736,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("938")]
    Item938,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("752")]
    Item752,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("702")]
    Item702,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("654")]
    Item654,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("705")]
    Item705,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("703")]
    Item703,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("694")]
    Item694,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("706")]
    Item706,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("740")]
    Item740,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("678")]
    Item678,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("222")]
    Item222,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("760")]
    Item760,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("748")]
    Item748,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("764")]
    Item764,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("972")]
    Item972,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("795")]
    Item795,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("788")]
    Item788,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("776")]
    Item776,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("626")]
    Item626,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("792")]
    Item792,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("949")]
    Item949,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("780")]
    Item780,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("901")]
    Item901,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("834")]
    Item834,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("980")]
    Item980,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("800")]
    Item800,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("840")]
    Item840,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("997")]
    Item997,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("998")]
    Item998,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("858")]
    Item858,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("860")]
    Item860,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("862")]
    Item862,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("937")]
    Item937,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("704")]
    Item704,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("548")]
    Item548,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("882")]
    Item882,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("950")]
    Item950,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("951")]
    Item951,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("960")]
    Item960,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("952")]
    Item952,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("953")]
    Item953,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("886")]
    Item886,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("891")]
    Item8911,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("710")]
    Item710,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("894")]
    Item894,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("716")]
    Item716,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public partial class RedemptionItems {
    
    private RedemptionItem redemptionItemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RedemptionItem redemptionItem {
        get {
            return this.redemptionItemField;
        }
        set {
            this.redemptionItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public partial class Campaign {
    
    private string titleField;
    
    private string textField;
    
    private RewardType rewardTypeField;
    
    private CampaignType campaignTypeField;
    
    private ulong valueField;
    
    private CurrencyType valueCurrField;
    
    private bool valueCurrFieldSpecified;
    
    private string appliedField;
    
    private ulong campaignPointsField;
    
    private bool campaignPointsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RewardType rewardType {
        get {
            return this.rewardTypeField;
        }
        set {
            this.rewardTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CampaignType campaignType {
        get {
            return this.campaignTypeField;
        }
        set {
            this.campaignTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CurrencyType valueCurr {
        get {
            return this.valueCurrField;
        }
        set {
            this.valueCurrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueCurrSpecified {
        get {
            return this.valueCurrFieldSpecified;
        }
        set {
            this.valueCurrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string applied {
        get {
            return this.appliedField;
        }
        set {
            this.appliedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong campaignPoints {
        get {
            return this.campaignPointsField;
        }
        set {
            this.campaignPointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool campaignPointsSpecified {
        get {
            return this.campaignPointsFieldSpecified;
        }
        set {
            this.campaignPointsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public enum RewardType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public enum CampaignType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public partial class Campaigns {
    
    private Campaign campaignField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Campaign campaign {
        get {
            return this.campaignField;
        }
        set {
            this.campaignField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public partial class MerchantReceipt {
    
    private bool adminField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool admin {
        get {
            return this.adminField;
        }
        set {
            this.adminField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
public enum DisplayType {
    
    /// <remarks/>
    CARDHOLDER,
    
    /// <remarks/>
    ATTENDANT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("confirmationResponse", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class ConfirmationResponse {
    
    private byte resultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public byte result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("timeoutNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class TimeoutNotification {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("displayNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class DisplayNotification {
    
    private Display displayField;
    
    private string minDisplayTimeField;
    
    private DisplayType displayTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Display display {
        get {
            return this.displayField;
        }
        set {
            this.displayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string minDisplayTime {
        get {
            return this.minDisplayTimeField;
        }
        set {
            this.minDisplayTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DisplayType displayType {
        get {
            return this.displayTypeField;
        }
        set {
            this.displayTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("printerNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class PrinterNotification {
    
    private MerchantReceipt merchantReceiptField;
    
    private string cardholderReceiptField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MerchantReceipt merchantReceipt {
        get {
            return this.merchantReceiptField;
        }
        set {
            this.merchantReceiptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cardholderReceipt {
        get {
            return this.cardholderReceiptField;
        }
        set {
            this.cardholderReceiptField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("loyPromotionNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class LoyaltyPromotionNotification {
    
    private ulong originalAmountField;
    
    private CurrencyType originalAmountCurrField;
    
    private Campaigns campaignsField;
    
    private RedemptionItems availableRedemptionItemsField;
    
    private PointBalance pointBalanceField;
    
    private ulong netAmountField;
    
    private bool netAmountFieldSpecified;
    
    private CurrencyType netAmountCurrField;
    
    private bool netAmountCurrFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong originalAmount {
        get {
            return this.originalAmountField;
        }
        set {
            this.originalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CurrencyType originalAmountCurr {
        get {
            return this.originalAmountCurrField;
        }
        set {
            this.originalAmountCurrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Campaigns campaigns {
        get {
            return this.campaignsField;
        }
        set {
            this.campaignsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RedemptionItems availableRedemptionItems {
        get {
            return this.availableRedemptionItemsField;
        }
        set {
            this.availableRedemptionItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PointBalance pointBalance {
        get {
            return this.pointBalanceField;
        }
        set {
            this.pointBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong netAmount {
        get {
            return this.netAmountField;
        }
        set {
            this.netAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool netAmountSpecified {
        get {
            return this.netAmountFieldSpecified;
        }
        set {
            this.netAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CurrencyType netAmountCurr {
        get {
            return this.netAmountCurrField;
        }
        set {
            this.netAmountCurrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool netAmountCurrSpecified {
        get {
            return this.netAmountCurrFieldSpecified;
        }
        set {
            this.netAmountCurrFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("loyAdviceNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class LoyaltyAdviceNotification {
    
    private ulong originalAmountField;
    
    private CurrencyType originalAmountCurrField;
    
    private Campaigns campaignsField;
    
    private RedemptionItems selectedRedemptionItemsField;
    
    private PointBalance pointBalanceField;
    
    private ulong netAmountField;
    
    private CurrencyType netAmountCurrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong originalAmount {
        get {
            return this.originalAmountField;
        }
        set {
            this.originalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CurrencyType originalAmountCurr {
        get {
            return this.originalAmountCurrField;
        }
        set {
            this.originalAmountCurrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Campaigns campaigns {
        get {
            return this.campaignsField;
        }
        set {
            this.campaignsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RedemptionItems selectedRedemptionItems {
        get {
            return this.selectedRedemptionItemsField;
        }
        set {
            this.selectedRedemptionItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PointBalance pointBalance {
        get {
            return this.pointBalanceField;
        }
        set {
            this.pointBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong netAmount {
        get {
            return this.netAmountField;
        }
        set {
            this.netAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CurrencyType netAmountCurr {
        get {
            return this.netAmountCurrField;
        }
        set {
            this.netAmountCurrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("abortCardEntryNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class AbortCardEntryNotification {
    
    private ushort abortCodeField;
    
    private bool abortCodeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ushort abortCode {
        get {
            return this.abortCodeField;
        }
        set {
            this.abortCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool abortCodeSpecified {
        get {
            return this.abortCodeFieldSpecified;
        }
        set {
            this.abortCodeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("manorTrxModificationRequest", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class ManorTrxModificationRequest {
    
    private string panField;
    
    private string applicationExpirationDateField;
    
    private string cardholderNameField;
    
    private byte brCodeField;
    
    private byte[] track3DataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pan {
        get {
            return this.panField;
        }
        set {
            this.panField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string applicationExpirationDate {
        get {
            return this.applicationExpirationDateField;
        }
        set {
            this.applicationExpirationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cardholderName {
        get {
            return this.cardholderNameField;
        }
        set {
            this.cardholderNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public byte brCode {
        get {
            return this.brCodeField;
        }
        set {
            this.brCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] track3Data {
        get {
            return this.track3DataField;
        }
        set {
            this.track3DataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("manorTrxModificationResponse", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class ManorTrxModificationResponse {
    
    private ulong amountField;
    
    private bool amountFieldSpecified;
    
    private string panField;
    
    private bool forceOnlineField;
    
    private bool forceOnlineFieldSpecified;
    
    private byte modResultField;
    
    private bool modResultFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ulong amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool amountSpecified {
        get {
            return this.amountFieldSpecified;
        }
        set {
            this.amountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pan {
        get {
            return this.panField;
        }
        set {
            this.panField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool forceOnline {
        get {
            return this.forceOnlineField;
        }
        set {
            this.forceOnlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool forceOnlineSpecified {
        get {
            return this.forceOnlineFieldSpecified;
        }
        set {
            this.forceOnlineFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public byte modResult {
        get {
            return this.modResultField;
        }
        set {
            this.modResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool modResultSpecified {
        get {
            return this.modResultFieldSpecified;
        }
        set {
            this.modResultFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("manorEnterAuthCodeResponse", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class EnterAuthCodeResponse {
    
    private string authCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string authCode {
        get {
            return this.authCodeField;
        }
        set {
            this.authCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("manorEnterAuthCodeRequest", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class EnterAuthCodeRequest {
    
    private Display displayField;
    
    private string timeoutField;
    
    private string timeoutReminderField;
    
    private DisplayType displayTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Display display {
        get {
            return this.displayField;
        }
        set {
            this.displayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string timeout {
        get {
            return this.timeoutField;
        }
        set {
            this.timeoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string timeoutReminder {
        get {
            return this.timeoutReminderField;
        }
        set {
            this.timeoutReminderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DisplayType displayType {
        get {
            return this.displayTypeField;
        }
        set {
            this.displayTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("cardEntryNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class CardEntryNotification {
    
    private uint cardEntryModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public uint cardEntryMode {
        get {
            return this.cardEntryModeField;
        }
        set {
            this.cardEntryModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("cardRemovalNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class CardRemovalNotification {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("trxStartNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class TrxStartNotification {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("trxEndNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class TrxEndNotification {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vibbek.com/device")]
[System.Xml.Serialization.XmlRootAttribute("trxAbortNotification", Namespace="http://www.vibbek.com/device", IsNullable=false)]
public partial class TrxAbortNotification {
}
